### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ShubhamJagtap2000** [navneetnivu07/nn#8]
I have a popular course(most recommended for beginners) about Machine Learning, AI from zero to hero, should I proceed?

**Comment by nivu** [comment]
@ShubhamJagtap2000 We stopped updating this repo. Checkout this repo for more recent content and make contributions to it.

**Comment by ShubhamJagtap2000** [comment]
> @ShubhamJagtap2000 We stopped updating this repo. Checkout this repo for more recent content and make contributions to it.

Okay, I will close this issue now.
